version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: ./webshell
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
