# Use an official Node runtime as the base image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy project files and folders to the current working directory (i.e. 'app' folder)
COPY . .

RUN npm run build

# Expose the port the app runs on
EXPOSE 3000

# Run the development server
CMD ["npm", "run", "prod"]
