/**
 * Format a summary into an IDENTITY.md file.
 */
export function formatIdentityMd(name: string, summary: string): string {
  return `# Identity: ${name}

## Summary

${extractSummaryContent(summary)}

## Metadata

- Generated by: YouSim Identity Constructor
- Generated at: ${new Date().toISOString()}
`;
}

/**
 * Format a summary into a SOUL.md file (for agent framework consumption).
 */
export function formatSoulMd(summary: string): string {
  const content = extractSummaryContent(summary);
  return `${content}
`;
}

/**
 * Extract content from <summary></summary> XML tags if present.
 */
function extractSummaryContent(summary: string): string {
  const match = summary.match(/<summary>([\s\S]*?)<\/summary>/);
  return match ? match[1].trim() : summary.trim();
}
